### PR TITLE
Small improvements to the Website

### PR DESCRIPTION
**Pull request by BastelPichi**
Small improvements like dots after hyperlinks...

### CODE REVIEW

**Comment by BastelPichi** [comment]
Dont merge the CNAMEs, Demo here: http://bunkercoin.pichisdns.com/

**Review by IdotMaster1 — APPROVED** [review]
Yo, Seems all good.. Just waiting for @sys-256, He is the brains of the site

**Comment by sys-256** [comment]
I'll review tomorrow github mobile suvks

**Comment by BastelPichi** [comment]
> I'll review tomorrow github mobile suvks

lol yesterday

**Review by sys-256 — COMMENTED** [review]
Hi, I personally don't really like having the dot excluded from the hyperlink, having the hyperlink end where the sentence ends as well is easier on the eyes in my opinion.

I do agree that the formatting here should be improves, but I don't think making it one long ass line is the way to go.
image

**Comment by BastelPichi** [comment]
> Hi, I personally don't really like having the dot excluded from the hyperlink, having the hyperlink end where the sentence ends as well is easier on the eyes in my opinion.
> 
> I do agree that the formatting here should be improves, but I don't think making it one long ass line is the way to go. image

Well... of course thats an personal oppinion... Originally I just wanted to remove the Hyperlinks that had more than 3 words, but then I quickly redid the rest of the site a bit...

**Comment by IdotMaster1** [comment]
Can someone fix the conflicting shit?

**Comment by BastelPichi** [comment]
Why approved but no merge?

**Comment by IdotMaster1** [comment]
sir it has a conflicting dick

**Comment by BastelPichi** [comment]
Yes because you didnt merge for like 3 months

**Comment by IdotMaster1** [comment]
F

**Comment by BastelPichi** [comment]
Actually like a year or something

**Comment by BastelPichi** [comment]
10 months

**Pull request closed without merging**
